version: "2.24"




services:
    db:
      image: postgres:15.6-alpine
      environment:
        POSTGRES_PASSWORD: 1234
        POSTGRES_USER: postgres
        POSTGRES_DB: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data/
  
    web:
      container_name: vapes
      build: . 
      command: bash -c "python /usr/src/vapeshop/manage.py migrate --noinput &&
                 python  /usr/src/vapeshop/manage.py runserver 0.0.0.0:8000"
      volumes: 
        - .:/usr/src/vapeshop
      ports:
        - 8000:8000
      
      depends_on:
        - db
        - redis
    redis:
      image: redis:latest
      container_name: redis
      ports:
        - "6379:6379"

volumes:
  postgres_data:
