# Generated by Django 4.2.10 on 2024-02-25 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_rating_ip_rating_user_alter_rating_star_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='product',
        ),
        migrations.AddField(
            model_name='rating',
            name='review',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.reviews'),
            preserve_default=False,
        ),
    ]
