# Generated by Django 4.2.10 on 2024-02-26 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayment',
            name='session_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
